### ISSUE TITLE
Gene set enrichment analysis

### ISSUE THREAD

**Issue by malonzm1** [timpeters82/DMRcate-devel#3]
Hi!

In performing gene set enrichment analysis on DMRcate output, how do I generate a background set? I tried setting the fdr in sequencing.annotate to 1.0 and pcutoff in dmrcate to 1.0 but I'm not sure if this is the right approach.

Thanks and good day.

**Comment by timpeters82** [comment]
Hi there,

Generating background sets for enrichment tests for DMRs is a contentious exercise, because no-one really knows how to reliably partition the genome into regulatory and non-regulatory regions. Feel free to use the strategy I described in the NAR paper (using complete list of Genehancer elements), but with the caveat that no background set can truly be _exhaustive_. 

You don't want to generate the background as you described - that will just give you enormous regions and won't be very meaningful.

Cheers,
Tim

**Comment by malonzm1** [comment]
Thanks!

In the paper you referred to (I think), it says "The background was defined as the complete list of genes with known interactions and promoter regions". Is this similar to using the whole genome?

**Comment by timpeters82** [comment]
> 

It's about as close as you can realistically get. Gene set enrichment is done in the HGNC space anyway, not in the genomic interval space. So any further attempt to granularise the background gives many-to-many mappings and hence risks ambiguity and degeneracy. Better to force your regions into the HGNC space as upstream as possible.
